base_model = "zhipuai/glm-5.3"
name = "GLM 5.3"

[interleaved]
field = "reasoning_content"

[[reasoning_options]]
type = "effort"
values = ["low", "high", "max"]

[cost]
input = 0.7677
output = 2.6807
cache_read = 0.1978
cache_write = 0

[limit]
context = 1_048_576
output = 1_048_576
